version: '3.4'

services:
    php:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: dom_handler_php
        volumes:
            - .:/var/www/html:rw
        container_name: dom_handler
