name: Sonars
on:
    push:
        branches:
            - develop
            - feature/*
            - feat/*
    pull_request:
        types: [ opened, synchronize, reopened ]
jobs:
    sonarcloud:
        name: Sonars
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP with Xdebug
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: xdebug

            -   name: Install dependencies with composer
                run: composer update --no-ansi --no-interaction --no-progress

            -   name: Generate coverage report with phpunit
                run: vendor/bin/phpunit --coverage-clover coverage.xml --log-junit report.xml --coverage-cobertura cobertura.xml

            -   name: Monitor coverage
                uses: slavcodev/coverage-monitor-action@v1
                with:
                    github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
                    coverage_path: coverage.xml
                    threshold_alert: 90
                    threshold_warning: 95

            -   name: Code Coverage Summary
                uses: irongut/CodeCoverageSummary@v1.3.0
                with:
                    filename: cobertura.xml
                    badge: true
                    fail_below_min: true
                    format: markdown
                    output: file
                    thresholds: '90 95'

            -   name: Add Coverage PR Comment
                uses: marocchino/sticky-pull-request-comment@v2
                with:
                    path: code-coverage-results.md

            -   name: Coverage Diff
                uses: clearlyip/code-coverage-report-action@v1.1.1
                with:
                    filename: coverage.xml

            -   name: Codecov analyze
                uses: codecov/codecov-action@v3
                with:
                    files: coverage.xml

            -   name: Fix phpunit files paths
                run: sed -i 's@'$GITHUB_WORKSPACE/'@''@g' coverage.xml report.xml

            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
